import { readFileSync } from 'node:fs';
import { defineConfig } from 'astro/config';
import starlight from '@astrojs/starlight';

// Guard against a polluted BASE_URL in the shell environment. Some dev
// setups export e.g. `BASE_URL=http://localhost:3000`; at SSR Astro reads
// `import.meta.env.BASE_URL` from process.env, so an absolute value would
// prefix every Starlight nav / favicon / sitemap link with localhost. The
// site's base is always "/", so drop any absolute inherited BASE_URL.
if (process.env.BASE_URL && /^[a-z][a-z0-9+.-]*:\/\//i.test(process.env.BASE_URL)) {
  delete process.env.BASE_URL;
}

// Custom Hale TextMate grammar → registered with Starlight's code blocks
// (Expressive Code) so spec `hale` fences are highlighted like the rest
// of the site.
const haleGrammar = JSON.parse(
  readFileSync(new URL('./src/grammars/hale.tmLanguage.json', import.meta.url), 'utf8')
);

// The docs sidebar mirrors the Book's SUMMARY.md — generated by
// scripts/sync-docs.mjs (run it first if this file is missing). The spec
// reference is site-only, so it's grafted onto the Book's Reference group.
const bookSidebar = JSON.parse(
  readFileSync(new URL('./src/generated/book-sidebar.json', import.meta.url), 'utf8')
);
(bookSidebar.find((g) => g.label === 'Reference') ?? bookSidebar.at(-1)).items.push(
  { label: 'Specification', collapsed: true, items: [{ autogenerate: { directory: 'docs/spec' } }] }
);

// https://astro.build/config
export default defineConfig({
  site: 'https://hale-lang.org',
  redirects: {
    '/agents': '/tooling',
    // The roadmap became a descriptive feature list — a roadmap
    // advertises intent and rots; /features describes what ships.
    '/roadmap': '/features',
    // The series titles were normalized (effects / claims /
    // constitutions / fleets); the old slug is linked from the
    // compiler repo's docs and anywhere the article traveled.
    '/articles/claim-driven-development-in-hale': '/articles/claims-in-hale',
  },
  integrations: [
    starlight({
      title: 'Hale',
      description: 'The Hale programming language documentation.',
      logo: { src: './public/favicon.svg', alt: 'Hale' },
      customCss: ['./src/styles/starlight.css'],
      components: {
        Header: './src/components/StarlightHeader.astro',
      },
      expressiveCode: {
        themes: ['github-dark'],
        shiki: { langs: [haleGrammar] },
      },
      social: [
        { icon: 'github', label: 'GitHub', href: 'https://github.com/hale-lang' },
      ],
      // Custom landing pages own the site root; Starlight serves /docs/*.
      sidebar: [
        ...bookSidebar,
        {
          label: 'Ecosystem',
          items: [
            { label: 'Packages (pond)', link: '/packages' },
            { label: 'For agents / LLMs', link: '/agents' },
          ],
        },
      ],
    }),
  ],
  markdown: {
    shikiConfig: { theme: 'github-dark' },
  },
});
