import { readFileSync, readdirSync, writeFileSync } from 'node:fs';
import { defineConfig } from 'astro/config';
import starlight from '@astrojs/starlight';
import glossTerms from './src/integrations/gloss.mjs';
import { haleLight, haleDark, haleGrammar } from './src/code/themes.mjs';

/*
  The text-only tree promises no script and no stylesheet of ours. It renders
  the same collections as the styled site, so it inherits that pipeline's
  assets: Astro's page script, and Expressive Code's copy-button JS and CSS
  that ride along with any rendered code fence.

  Neither is opt-out-able per route, and the alternative — parsing the
  markdown ourselves — would fork the content pipeline for the sake of a tag.
  So strip the references once the build is written. The pages then are what
  they claim to be: semantic HTML and the reader's own defaults.
*/
function textOnlyAssets() {
  return {
    name: 'text-only-assets',
    hooks: {
      'astro:build:done': ({ dir, logger }) => {
        const walk = (u) => readdirSync(u, { withFileTypes: true }).flatMap((e) =>
          e.isDirectory() ? walk(new URL(`${e.name}/`, u)) : [new URL(e.name, u)]);
        let n = 0;
        for (const file of walk(new URL('text/', dir))) {
          if (!file.pathname.endsWith('.html')) continue;
          const before = readFileSync(file, 'utf8');
          const after = before
            .replace(/<script\b[^>]*>[\s\S]*?<\/script>/g, '')
            .replace(/<link\b[^>]*rel=["']stylesheet["'][^>]*>/g, '');
          if (after !== before) {
            writeFileSync(file, after);
            n++;
          }
        }
        logger.info(`text-only: stripped script and stylesheet refs from ${n} pages`);
      },
    },
  };
}

// Guard against a polluted BASE_URL in the shell environment. Some dev
// setups export e.g. `BASE_URL=http://localhost:3000`; at SSR Astro reads
// `import.meta.env.BASE_URL` from process.env, so an absolute value would
// prefix every Starlight nav / favicon / sitemap link with localhost. The
// site's base is always "/", so drop any absolute inherited BASE_URL.
if (process.env.BASE_URL && /^[a-z][a-z0-9+.-]*:\/\//i.test(process.env.BASE_URL)) {
  delete process.env.BASE_URL;
}

// The Hale grammar and the two code themes (src/code/) are shared by the
// Hale component, article fences and the docs' Expressive Code, so a listing
// is coloured the same everywhere and follows the reader's theme.
const FONTS = 'https://fonts.googleapis.com/css2?family=Literata:ital,opsz,wght@0,7..72,400;0,7..72,500;0,7..72,600;1,7..72,400;1,7..72,500&family=JetBrains+Mono:wght@400;500;700&display=swap';

// The docs sidebar mirrors the Book's SUMMARY.md — generated by
// scripts/sync-docs.mjs (run it first if this file is missing). The spec
// reference is site-only, so it's grafted onto the Book's Reference group.
const bookSidebar = JSON.parse(
  readFileSync(new URL('./src/generated/book-sidebar.json', import.meta.url), 'utf8')
);
(bookSidebar.find((g) => g.label === 'Reference') ?? bookSidebar.at(-1)).items.push(
  { label: 'Specification', collapsed: true, items: [{ autogenerate: { directory: 'docs/spec' } }] }
);

// https://astro.build/config
export default defineConfig({
  site: 'https://hale-lang.org',
  redirects: {
    '/agents': '/tooling',
    // The roadmap became a descriptive feature list — a roadmap
    // advertises intent and rots; /features describes what ships.
    '/roadmap': '/features',
    // The series titles were normalized (effects / claims /
    // constitutions / fleets); the old slug is linked from the
    // compiler repo's docs and anywhere the article traveled.
    '/articles/claim-driven-development-in-hale': '/articles/claims-in-hale',
    // /why was a byte-identical copy of /model. One page, one URL.
    '/why': '/model',
  },
  integrations: [
    textOnlyAssets(),
    glossTerms(),
    starlight({
      title: 'Hale',
      description: 'The Hale programming language documentation.',
      logo: { src: './public/favicon.svg', alt: 'Hale' },
      customCss: ['./src/styles/starlight.css'],
      components: {
        Header: './src/components/StarlightHeader.astro',
      },
      head: [
        { tag: 'link', attrs: { rel: 'preconnect', href: 'https://fonts.googleapis.com' } },
        { tag: 'link', attrs: { rel: 'preconnect', href: 'https://fonts.gstatic.com', crossorigin: '' } },
        { tag: 'link', attrs: { rel: 'stylesheet', href: FONTS } },
      ],
      expressiveCode: {
        themes: [haleDark, haleLight],
        shiki: { langs: [haleGrammar] },
        styleOverrides: {
          borderRadius: '4px',
          borderColor: 'var(--hair)',
          codeFontFamily: "'JetBrains Mono', ui-monospace, Menlo, Consolas, monospace",
          codeFontSize: '0.84rem',
          uiFontFamily: "'JetBrains Mono', ui-monospace, Menlo, Consolas, monospace",
          frames: { shadowColor: 'transparent' },
        },
      },
      social: [
        { icon: 'github', label: 'GitHub', href: 'https://github.com/hale-lang' },
      ],
      // Custom landing pages own the site root; Starlight serves /docs/*.
      sidebar: [
        ...bookSidebar,
        {
          label: 'Ecosystem',
          items: [
            { label: 'Packages (pond)', link: '/packages' },
            { label: 'For agents / LLMs', link: '/agents' },
          ],
        },
      ],
    }),
  ],
  markdown: {
    shikiConfig: { themes: { light: haleLight, dark: haleDark }, langs: [haleGrammar] },
  },
});
